# ── Base de datos (H2 en memoria por defecto, cambia si usas otra) ─────────────
spring.datasource.url=${DATABASE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# ── Configuración de correo Gmail ─────────────────────────────────────────────
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ── Otros ─────────────────────────────────────────────────────────────────────
spring.h2.console.enabled=false
spring.jpa.open-in-view=false

# Debuggear el envío de correos ────────────────────────────────────────────────
logging.level.org.springframework.mail=DEBUG
logging.level.javax.mail=DEBUG

# Contraseña de aplicación de Gmail (sacarla con la verificacion en dos pasos y contraseñas de 
# aplicaciones de cuenta de Google https://myaccount.google.com/apppasswords)

# spring.mail.password=nryjtwatskzyemfy
# spring.mail.properties.mail.smtp.auth=true
# spring.mail.properties.mail.smtp.starttls.enable=true

## Manejo de la base de datos H2 local (consola web) 
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console


