# ── Base de datos (H2 en memoria por defecto, cambia si usas otra) ─────────────
spring.datasource.url=jdbc:h2:file:./katodo-db
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=update

# ── Configuración de correo Gmail ─────────────────────────────────────────────
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=katodociberjoyeria@gmail.com

# Contraseña de aplicación de Gmail (sacarla con la verificacion en dos pasos y contraseñas de 
# aplicaciones de cuenta de Google https://myaccount.google.com/apppasswords)
spring.mail.password=nryjtwatskzyemfy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

logging.level.org.springframework.mail=DEBUG
logging.level.javax.mail=DEBUG

# Manejo de la base de datos H2 (consola web)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console